# MODIFY THE TITLE TO local_secrets.py WHEN YOU ACTUALLY USE IT
# MODIFY THIS FILE WITH YOUR OWN KEYS AND TOKENS

GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"
HUGGINGFACE_TOKEN = "YOUR_HUGGINGFACE_TOKEN_HERE"